### ISSUE TITLE
Updated docker image?

### ISSUE THREAD

**Issue by StagnationPoint** [ronald-den-otter/omada-sdn-controller#1]
Thanks for putting this together! Any chance you could toss up an updated docker image with the 4.x SDN version?

**Comment by ronald-den-otter** [comment]
4.2.4-1 is currently latest version. But I noticed url's in readme were incorrect.
docker pull ronaldo1965/omada-sdn-controller
or
docker pull ronaldo1965/omada-sdn-controller:4.2.4-1
